import os

# ==== Notion ====
NOTION_API_KEY = os.getenv("NOTION_API_KEY")
HEADERS = {
    "Authorization": f"Bearer {NOTION_API_KEY}",
    "Notion-Version": "2022-06-28"
}

MASTER_DATABASE_ID = os.getenv("NOTION_DATABASE_ID")
# NOTION_CATEGORY_PROPERTY = os.getenv("NOTION_CATEGORY_PROPERTY", "Category")
# NOTION_CATEGORY_PROPERTY_TYPE = os.getenv("NOTION_CATEGORY_PROPERTY_TYPE", "select")
NOTION_CATEGORY_PROPERTY = "複合動詞"
NOTION_CATEGORY_PROPERTY_TYPE = "checkbox"
# ==== Discord ====
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
DISCORD_USER_ID = os.getenv("DISCORD_USER_ID")
DISCORD_USER_HIEN_ID = os.getenv("DISCORD_USER_HIEN_ID")